version: '2'
services:
    app:
        build:
            context: .test_sincos/application
            args:
                - PATH_TO_PROJECT=/var/www/test_sincos.app
        container_name: testsincos.app
        volumes:
          - ./application:/var/www/test_sincos.app
        tty: true
    nginx:
        build:
            context: .test_sincos/nginx
        container_name: testsincos_nginx
        volumes_from:
            - app
        volumes:
            - ./logs/nginx/:/var/log/nginx
        ports:
            - "80:80"
            - "443:443"
        links:
            - php-fpm
    php-fpm:
        build:
            context: .test_sincos/php_fpm
        container_name: testsincos_php-fpm
        volumes_from:
            - app
        expose:
            - "9000"
        links:
            - app
    mariadb:
        build:
            context: .test_sincos/mariadb
        container_name: testsincos_mariadb
        volumes_from:
            - app
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: sawfly
            MYSQL_USER: sawfly
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root